### ISSUE TITLE
 No such file or directory:

### ISSUE THREAD

**Issue by zzzzjx** [Bohao-Lee/CME#15]
Thanks for your great job. I meet this error when I run the train_model.sh
Traceback (most recent call last):
  File "tool/valid_decoupling.py", line 218, in <module>
    valid(datacfg, darknet, learnet, weightfile, outfile, use_baserw)
  File "tool/valid_decoupling.py", line 36, in valid
    m.load_weights(weightfile)
  File "/home/zjx/CME/tool/darknet/darknet_decoupling.py", line 379, in load_weights
    fp = open(weightfile, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'backup/split1_10shot/000010.weights'

How to solve it . Waiting for your reply.

**Comment by miznchimaki** [comment]
Hello,guy!
I also use this project and met the problem you describe a few days ago. I think the error `No such file or directory` may not be the true error you met, because if you had an error in the base training phase, it will go on running finetuning and test weights codes in training scripts `train_model.sh`. So I suggest you commenting out the finetuning and test weights code lines in training scripts `train_model.sh`, then you can see the true error you met in the base training phase. For me the error is `CUDA out of memory`(My gpu is 2080 Ti, its memory is much lower than Tesla V100). Hope you can find your problem and solve it!
